### ISSUE TITLE
[Suggestion] Godot Engine instead of Unity Engine?

### ISSUE THREAD

**Issue by ls-1N** [pjasicek/OpenMM8#3]
I think an open-source engine would be more suitable for an open-source project. There are also a few actual advantages to using an open-source engine that I can think of:

* Distributing the game in ways that require the whole software to be fully open-source (like many Linux and other OS repositories). 
* Not dependent on Unity's team's decisions: When they happen to decide to drop support for something (1080p, 2D screens, Windows 7, Linux, 16:10 aspect ratio, certain frameworks or APIs) or when they decide they actually don't like having a free version of the engine or something else annoying - there's nothing we can do, whilst in an open-source environment, someone will continue supporting those. And even if no one did (has to be real niche need), this game's community could continue the support (or hire someone). 
* Easier support in the longer term - don't have to follow any and all of their arbitrary decisions - we can always stay on an older version of the engine or fork.

**Comment by pjasicek** [comment]
Hi, since this is a pet project of mine and pretty much all of the core mechanics are working I am not planning to switch game engines. So far I am really happy with using Unity, at first I tried it in UE4, but that was really cumbersome.

Nonetheless, thanks for the suggestion.
